name: StandardPlugin
main: com.sbezboro.standardplugin.StandardPlugin
version: 2.6.24
softdepend: [JSONAPI, SimplyVanish, Essentials, Factions]
api-version: 1.16

commands:
    standard:
        description: Base command
        permission: standardplugin.standard
        permission-message: You don't have permission
    register:
        description: Register a website account with your Minecraft username
        permission: standardplugin.register
        permission-message: You don't have permission
        aliases: [forum]
    rank:
        description: Check out your rank on the website
        permission: standardplugin.rank
        permission-message: You don't have permission
    unfreeze:
        description: Use this command to unfreeze yourself
        permission: standardplugin.unfreeze
        permission-message: You don't have permission
        aliases: [u]
    spawn:
        description: See the coordinates of the various spawn areas
        permission: standardplugin.spawn
        permission-message: You don't have permission
        aliases: [spawns, spawncoords]
    gate:
        description: Set up gates
        permission: standardplugin.gate
        permission-message: You don't have permission
    setspawn:
        description: Set spawn
        permission: standardplugin.setspawn
        permission-message: You don't have permission
    forummute:
        description: Hide forum post notifications from chat for certain users
        permission: standardplugin.forummute
        permission-message: You don't have permission
    enablepvp:
        description: Disable your PVP protection early
        permission: standardplugin.enablepvp
        permission-message: You don't have permission
    pvp:
        description: Query/enable/disable pvp protection for players
        permission: standardplugin.pvp
        permission-message: You don't have permission
    sstitle:
        description: Administrate player titles
        permission: standardplugin.sstitle
        permission-message: You don't have permission
    titles:
        description: Check out titles for a player
        permission: standardplugin.titles
        permission-message: You don't have permission
    webchat:
        description: See who's online on web chat
        permission: standardplugin.webchat
        permission-message: You don't have permission
    end:
        description: End reset tools
        permission: standardplugin.end
        permission-message: You don't have permission
    clearbed:
        description: Clears your bed spawn for when you cant break the bed
        permission: standardplugin.clearbed
        permission-message: You don't have permission
        aliases: [resetbed, resetspawn]
    honeypot:
        description: Honeypot administration
        permission: standardplugin.honeypot
        permission-message: You don't have permission
    endreset:
        description: Find out when the next end reset is
        permission: standardplugin.endreset
        permission-message: You don't have permission
    usernames:
        description: See past usernames of a player
        permission: standardplugin.usernames
        permission-message: You don't have permission

permissions:
    standardplugin.standard:
        default: op
    standardplugin.register:
        default: true
    standardplugin.rank:
        default: true
    standardplugin.unfreeze:
        default: true
    standardplugin.spawn:
        default: true
    standardplugin.gate:
        default: op
    standardplugin.setspawn:
        default: op
    standardplugin.forummute:
        default: op
    standardplugin.enablepvp:
        default: true
    standardplugin.pvp:
        default: op
    standardplugin.title:
        default: op
    standardplugin.titles:
        default: true
    standardplugin.webchat:
        default: true
    standardplugin.end:
        default: op
    standardplugin.clearbed:
        default: true
    standardplugin.honeypot:
        default: op
    standardplugin.endreset:
        default: true
    standardplugin.usernames:
        default: true
    standardplugin.moderator:
        default: op
